spring.application.name=audio-transcribe
spring.ai.openai.api-key=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
spring.ai.openai.audio.transcription.base-url=https://api.openai.com
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.response-format=json